
#微服务配置
spring:
  application:
    name: learning-api
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        namespace: dev
        group: xuecheng
      config:
        namespace: dev
        group: xuecheng
        file-extension: yaml
        refresh-enabled: true
        extension-configs:
          - data-id: learning-service-${spring.profiles.active}.yaml
            group: xuecheng
            refresh: true
        shared-configs:
          - data-id: log-${spring.profiles.active}.yaml
            group: xuecheng
            refresh: true
          - data-id: feign-${spring.profiles.active}.yaml
            group: xuecheng
            refresh: true

  profiles:
    active: dev
  config:
    import:
      - nacos:${spring.application.name}-${spring.profiles.active}.yaml
      - nacos:learning-service-${spring.profiles.active}.yaml
      - nacos:log-${spring.profiles.active}.yaml
      - nacos:feign-${spring.profiles.active}.yaml

  security:
    oauth2:
      # 资源服务器配置
      resourceserver:
        jwt:
          # Jwt中claims的iss属性，也就是jwt的签发地址，即认证服务器的根路径
          # 资源服务器会进一步的配置，通过该地址获取公钥以解析jwt
          issuer-uri: http://10.198.114.1:8160/auth
