spring:
  application:
    name: gateway
  config:
    import:
      - nacos:gateway-dev.yaml
      - nacos:log-dev.yaml
  cloud:
    nacos:
      #      server-addr: nacos:8848 # nacos地址
      server-addr: localhost:8848 # nacos地址
      discovery:
        namespace: dev
        group: xuecheng
      config:
        # 配置文件优先级：nacos:config -> nacos:extension-configs -> nacos:shared-configs -> 本地配置文件
        prefix: ${spring.application.name}
        file-extension: yaml
        namespace: dev
        group: xuecheng
        shared-configs:
          - data-id: log-dev.yaml
            group: xuecheng
            refresh: true

  profiles:
    active: dev

security:
  whitelist:
    - /** # 暂时全部开放
    - /auth/**
    - /content/open/**
    - /media/open/**
