#微服务配置
spring:
  main:
    allow-circular-references: true
  config:
    import:
      - nacos:${spring.application.name}-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}
      - nacos:log-${spring.profiles.active}.yaml
      - nacos:freemarker-config-${spring.profiles.active}.yaml
  application:
    name: content-api
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        namespace: ${spring.profiles.active}
        group: xuecheng
      config:
        namespace: ${spring.profiles.active}
        group: xuecheng
        file-extension: yaml
        refresh-enabled: true
        shared-configs:
          - data-id: log-${spring.profiles.active}.yaml
            group: xuecheng
            refresh: true
          - data-id: feign-${spring.profiles.active}.yaml
            group: xuecheng
            refresh: true
  profiles:
    active: dev
  security:
    oauth2:
      # 资源服务器配置
      resourceserver:
        jwt:
          # Jwt中claims的iss属性，也就是jwt的签发地址，即认证服务器的根路径
          # 资源服务器会进一步的配置，通过该地址获取公钥以解析jwt
          issuer-uri: http://localhost:63070/auth