spring:
  main:
    allow-circular-references: true
  config:
    import:
      - nacos:auth-service-${spring.profiles.active}.yaml
      - nacos:log-${spring.profiles.active}.yaml
  application:
    name: auth-service
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        namespace: ${spring.profiles.active}
        group: xuecheng
      config:
        namespace: ${spring.profiles.active}
        group: xuecheng
        file-extension: yaml
        refresh-enabled: true
        shared-configs:
          - data-id: log-${spring.profiles.active}.yaml
            group: xuecheng
            refresh: true

  profiles:
    active: dev
